; =====================================================
; TORRE — game-torre
; NodeMCU ESP8266 + Fita WS2812B 30 LEDs + 2x LDR
;                + DFPlayer Mini (caixa de som)
; Ambiente: VS Code + PlatformIO (Windows)
; =====================================================
[env:nodemcuv2]
platform      = espressif8266
board         = nodemcuv2
framework     = arduino
monitor_speed = 115200

lib_deps =
    fastled/FastLED                  @ ^3.6.0
    knolleary/PubSubClient           @ ^2.8
    bblanchon/ArduinoJson            @ ^6.21.3
    dfrobot/DFRobotDFPlayerMini      @ ^1.0.6
